version: "3"

services:

  nginx:
    container_name: nginx
    image: nginx:stable
    volumes:
      - ./nginx/dev/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/ssl
      - ./resources:/resources
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web

  web:
    container_name: react_app
    restart: on-failure
    build:
      context: .
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    ports:
      - "3000:3000"
    command: >
      sh -c "npm start"
    env_file:
      - .env
    environment:
      CHOKIDAR_USEPOLLING: "true"

  backend:
    container_name: backend
    build:
      context: ./backend
    ports:
      - "5005:5005"
    command: uvicorn api.main:app --host 0.0.0.0 --port 5005
    env_file:
      - .env
