version: "3"

services:

  nginx:
    container_name: nginx
    volumes:
      - ./nginx/staging/nginx.conf:/etc/nginx/conf.d/default.conf
      - ../ssl/dhparam.pem:/etc/nginx/dhparam.pem
      - ./build:/app/staging
      - ./resources:/resources
      - ../ssl:/etc/ssl
    restart: on-failure
    image: nginx:stable
    ports: 
      - "80:80"
      - "443:443"

  backend:
    container_name: backend
    build:
      context: ./backend
    ports:
      - "5005:5005"
    command: uvicorn api.main:app --host 0.0.0.0 --port 5005
    env_file:
      - ../.env
