name: Deploy with a specific branch

env:
  targetFolder: "/home/ubuntu/deploy/landing"

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Branch name'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.name }}

      - name: Use Node.JS 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm install

      - name: Build
        env:
          NODE_OPTIONS: "--max-old-space-size=8192"
        run: npm run build

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          SOURCE: "build/"
          TARGET: ${{ env.targetFolder }}
